--liquibase formatted sql

--changeset CHANDRAMANI:METADATA_OVERRIDE_TBL_1 runOnChange:true failOnError:true
--comment metadata reference table for stage load key override information
CREATE OR REPLACE TABLE METADATA_OVERRIDE_TBL (
	DATASOURCE VARCHAR(16777216) COMMENT 'BODS Extract Structure',
	TABLE_NAME VARCHAR(16777216) COMMENT 'SAP Table Name',
	FIELDNAME VARCHAR(16777216) COMMENT 'Name Of Extract Column',
	KEYFLAG VARCHAR(16777216) COMMENT 'Key Column flag (currently all records are key columns)',
	ELEMENT VARCHAR(16777216) COMMENT 'SAP Data Element',
	TYPE VARCHAR(16777216) COMMENT 'SAP Data Type',
	LENGTH NUMBER(38,0),
	DESCRIPTION VARCHAR(16777216) COMMENT 'Column Description',
	INSERT_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP() COMMENT 'Time Stamp Of Row Insert'
) COMMENT='Custom Key Metadata to load SAP tables (manually provided data)'
;

--changeset bob.carey:METADATA_OVERRIDE_TBL_LOAD_1 runOnChange:true failOnError:true
--comment Load the manually generated Key Information into the metadata reference table for stage load key override
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0ACTTYPE_ATTR', 'CSLA', 'KOKRS', 'X', 'KOKRS', 'CHAR', 4, 'Controlling Area');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0ACTTYPE_ATTR', 'CSLA', 'LSTAR', 'X', 'LSTAR', 'CHAR', 6, 'Activity Type');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0ACTTYPE_ATTR', 'CSLA', 'DATETO', 'X', 'DATBI', 'DATS', 8, 'Valid To Date');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0COSTCENTER_TEXT', 'CSKT', 'LANGU', 'X', 'SPRAS', 'LANG', 1, 'Language Key');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0COSTCENTER_TEXT', 'CSKT', 'KOKRS', 'X', 'KOKRS', 'CHAR', 4, 'Controlling Area');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0COSTCENTER_TEXT', 'CSKT', 'KOSTL', 'X', 'KOSTL', 'CHAR', 10, 'Cost Center');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0COSTCENTER_TEXT', 'CSKT', 'DATETO', 'X', 'DATBI', 'DATS', 8, 'Valid To Date');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0MATERIAL_TEXT', 'MAKT ', 'MATNR', 'X', 'MATNR', 'CHAR', 40, 'Material Number');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0MATERIAL_TEXT', 'MAKT ', 'SPRAS', 'X', 'SPRAS', 'LANG', 1, 'Language Key');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0MAT_SALES_ATTR', 'MVKE', 'MATNR', 'X', 'MATNR', 'CHAR', 40, 'Material Number');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0MAT_SALES_ATTR', 'MVKE', 'VKORG', 'X', 'VKORG', 'CHAR', 4, 'Sales Organization');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0MAT_SALES_ATTR', 'MVKE', 'VTWEG', 'X', 'VTWEG', 'CHAR', 2, 'Distribution Channel');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0MAT_ST_LOC_ATTR', 'MARD', 'MATNR', 'X', 'MATNR', 'CHAR', 40, 'Material Number');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0MAT_ST_LOC_ATTR', 'MARD', 'WERKS', 'X', 'WERKS_D', 'CHAR', 4, 'Plant');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0MAT_ST_LOC_ATTR', 'MARD', 'LGORT', 'X', 'LGORT_D', 'CHAR', 4, 'Storage Location');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0MAT_VEND_ATTR', 'EINA?', 'INFNR', 'X', 'INFNR', 'CHAR', 10, 'Number of purchasing info record');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0MAT_VEND_ATTR', 'EINA?', 'MATNR', 'X', 'MATNR', 'CHAR', 40, 'Material Number');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0MAT_VEND_ATTR', 'EINA?', 'LIFNR', 'X', 'ELIFN', 'CHAR', 10, 'Vendors account number');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0PROFIT_CTR_ATTR', 'CEPC', 'PRCTR', 'X', 'PRCTR', 'CHAR', 10, 'Profit Center');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0PROFIT_CTR_ATTR', 'CEPC', 'DATETO', 'X', 'DATBI', 'DATS', 8, 'Valid To Date');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0PROFIT_CTR_ATTR', 'CEPC', 'KOKRS', 'X', 'KOKRS', 'CHAR', 4, 'Controlling Area');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0PROFIT_CTR_TEXT', 'CEPCT', 'LANGU', 'X', 'SPRAS', 'LANG', 1, 'Language Key');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0PROFIT_CTR_TEXT', 'CEPCT', 'PRCTR', 'X', 'PRCTR', 'CHAR', 10, 'Profit Center');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0PROFIT_CTR_TEXT', 'CEPCT', 'DATETO', 'X', 'DATBI', 'DATS', 8, 'Valid To Date');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0PROFIT_CTR_TEXT', 'CEPCT', 'KOKRS', 'X', 'KOKRS', 'CHAR', 4, 'Controlling Area');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0WBS_ELEMT_ATTR', 'PRPS', 'POSID', 'X', 'PS_POSNR', 'NUMC', 8, 'WBS Element');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0WBS_ELEMT_TEXT', 'PRPS', 'POSID', 'X', 'PS_POSNR', 'NUMC', 8, 'WBS Element');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0WBS_ELEMT_TEXT', 'PRPS', 'LANGU', 'X', 'SPRAS', 'LANG', 1, 'Language Key');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0FI_ACDOCA_10', 'ACDOCA', 'RCLNT', 'X', 'MANDT', 'CLNT', 3, 'Client');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0FI_ACDOCA_10', 'ACDOCA', 'RLDNR', 'X', 'FINS_LEDGER', 'CHAR', 2, 'Ledger in General Ledger Accounting');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0FI_ACDOCA_10', 'ACDOCA', 'RBUKRS', 'X', 'BUKRS', 'CHAR', 4, 'Company Code');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0FI_ACDOCA_10', 'ACDOCA', 'GJAHR', 'X', 'GJAHR', 'NUMC', 4, 'Fiscal Year');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0FI_ACDOCA_10', 'ACDOCA', 'BELNR', 'X', 'BELNR_D', 'CHAR', 10, 'Accounting Document Number');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('0FI_ACDOCA_10', 'ACDOCA', 'DOCLN', 'X', 'DOCLN6', 'CHAR', 6, 'Six-Character Posting Item for Ledger');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_02_ACC', 'EKKN', 'EBELN', 'X', 'EBELN', 'CHAR', 10, 'Purchasing Document Number');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_02_ACC', 'EKKN', 'EBELP', 'X', 'EBELP', 'NUMC', 5, 'Item Number of Purchasing Document');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_02_ACC', 'EKKN', 'ZEKKN', 'X', 'DZEKKN', 'NUMC', 2, 'Sequential Number of Account Assignment');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_02_ACC', '?', 'BUKRS', 'X', '', '', NULL, '');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_02_ACC', '?', 'LOGSY', 'X', '', '', NULL, '');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_02_ACC', '?', 'BWVORG', 'X', '', '', NULL, '');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_02_HDR', 'EKKO', 'EBELN', 'X', 'EBELN', 'CHAR', 10, 'Purchasing Document Number');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_02_ITM', 'EKPO', 'EBELN', 'X', 'EBELN', 'CHAR', 10, 'Purchasing Document Number');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_02_ITM', 'EKPO', 'EBELP', 'X', 'EBELP', 'NUMC', 5, 'Item Number of Purchasing Document');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_02_SCL', 'EKET', 'EBELN', 'X', 'EBELN', 'CHAR', 10, 'Purchasing Document Number');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_02_SCL', 'EKET', 'EBELP', 'X', 'EBELP', 'NUMC', 5, 'Item Number of Purchasing Document');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_02_SCL', 'EKET', 'ETENR', 'X', 'EETEN', 'NUMC', 4, 'Delivery Schedule Line Counter');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_03_BF', 'MSEG/MKPF', 'MBLNR', 'X', 'MBLNR', 'CHAR', 10, 'Number of Material Document');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_03_BF', 'MSEG/MKPF', 'MJAHR', 'X', 'MJAHR', 'NUMC', 4, 'Material Document Year');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_03_BF', 'MSEG', 'ZEILE', 'X', 'MBLPO', 'NUMC', 4, 'Item in Material Document');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_03_BF', '?', 'BWCOUNTER', 'X', '', '', NULL, 'Unique Identification of Document Line');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_03_BF', 'MBEW', 'BWKEY', 'X', 'BWKEY', 'CHAR', 4, 'Valuation area');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_03_BF', 'MBEW', 'BWTAR', 'X', 'BWTAR_D', 'CHAR', 10, 'Valuation Type');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_03_UM', 'BSEG', 'BUKRS', 'X', 'BUKRS', 'CHAR', 4, 'Company Code');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_03_UM', 'BSEG', 'BELNR', 'X', 'BELNR_D', 'CHAR', 10, 'Accounting Document Number');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_03_UM', 'BSEG', 'GJAHR', 'X', 'GJAHR', 'NUMC', 4, 'Fiscal Year');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_03_UM', 'BSEG', 'BUZEI', 'X', 'BUZEI', 'NUMC', 3, 'Number of Line Item Within Accounting Document');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_11_VAHDR', 'VBAK', 'VBELN', 'X', 'VBELN_VA', 'CHAR', 10, 'Sales Document');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_11_VAITM', 'VBAP', 'VBELN', 'X', 'VBELN_VA', 'CHAR', 10, 'Sales Document');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_11_VAITM', 'VBAP', 'POSNR', 'X', 'POSNR_VA', 'NUMC', 6, 'Sales Document Item');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_11_VASCL', 'VBEP', 'VBELN', 'X', 'VBELN_VA', 'CHAR', 10, 'Sales Document');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_11_VASCL', 'VBEP', 'POSNR', 'X', 'POSNR_VA', 'NUMC', 6, 'Sales Document Item');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_11_VASCL', 'VBEP', 'ETENR', 'X', 'ETENR', 'NUMC', 4, 'Schedule Line Number');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_13_VDHDR', 'VBRK', 'VBELN', 'X', 'VBELN_VF', 'CHAR', 10, 'Billing Document');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_13_VDITM', 'VBRP', 'VBELN', 'X', 'VBELN_VF', 'CHAR', 10, 'Billing Document');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_13_VDITM', 'VBRP', 'POSNR', 'X', 'POSNR_VF', 'NUMC', 6, 'Billing Item');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_13_VDKON', 'PRCD_ELEMENTS', 'KNUMV', 'X', 'KNUMV', 'CHAR', 10, 'Number of the Document Condition');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_13_VDKON', 'PRCD_ELEMENTS', 'KPOSN', 'X', 'KPOSN', 'NUMC', 6, 'Condition item number');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_13_VDKON', 'PRCD_ELEMENTS', 'STUNR', 'X', 'STUNR', 'NUMC', 3, 'Step Number');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('2LIS_13_VDKON', 'PRCD_ELEMENTS', 'ZAEHK', 'X', 'VFPRC_COND_COUNT', 'NUMC', 3, 'Condition Counter');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('ZDS_COND_CONT_PRICING', '?', 'COCO_NUM', 'X', '', '', NULL, '');
INSERT INTO METADATA_OVERRIDE_TBL (DATASOURCE, TABLE_NAME, FIELDNAME, KEYFLAG, ELEMENT, TYPE, LENGTH, DESCRIPTION) VALUES ('ZDS_COND_CONT_PRICING', '?', 'KNUMH', 'X', '', '', NULL, '');
