--liquibase formatted sql
				
--changeset CHANDRAMANI:YED_SALES_TEMP_3 runOnChange:true failOnError:true endDelimiter:""
--comment metadata type reference table
-----------------------------------------------------------------
--RECEF ID: RA_R2144 - CR   
--DATE: 2023-10-05
--DESCRIPTION: Date Dimension Table for Calender Year

-----------------------------------------------------------------
EXECUTE IMMEDIATE 
$$
BEGIN

create or replace TEMPORARY TABLE STAGE.YED_SALES_TEMP (
	REDISTID VARCHAR(16777216) COMMENT 'Redistributor ID',
	CUSTOMER VARCHAR(16777216) COMMENT 'Customer',
	DATE VARCHAR(16777216) COMMENT 'Date',
	ITEMID VARCHAR(16777216) COMMENT 'Item ID',
	CASES VARCHAR(16777216) COMMENT 'Cases',
	INVOICENO VARCHAR(16777216) COMMENT 'Invoice Number',
	CUSTNAME VARCHAR(16777216) COMMENT 'Customer Name',
	CUSTADDR VARCHAR(16777216) COMMENT 'Customer Address',
	CUSTCITYSTATE VARCHAR(16777216) COMMENT 'Customer City/State',
	CUSTZIPCODE VARCHAR(16777216) COMMENT 'Customer Zip Code',
	BILLTONAME VARCHAR(16777216) COMMENT 'Bill To Name',
	BILLTOADDR VARCHAR(16777216) COMMENT 'Bill To Address',
	BILLTOCITYSTATE VARCHAR(16777216) COMMENT 'Bill To City/State',
	BILLTOZIPCODE VARCHAR(16777216) COMMENT 'Bill To Zip Code',
	BUYGROUP VARCHAR(16777216) COMMENT 'Buy Group',
	BROKER VARCHAR(16777216) COMMENT 'Broker',
	FILENAME VARCHAR(16777216) COMMENT 'File Name',
	INSERT_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP() COMMENT 'Time Stamp Of Row Insert'
)COMMENT='Redistributor Sales EDI Data'
;

INSERT INTO STAGE.YED_SALES_TEMP 
SELECT REDISTID, CUSTOMER, DATE, ITEMID, CASES, INVOICENO, CUSTNAME, CUSTADDR, CUSTCITYSTATE, CUSTZIPCODE, BILLTONAME, BILLTOADDR, BILLTOCITYSTATE, BILLTOZIPCODE, BUYGROUP, BROKER, FILENAME, INSERT_DATETIME
FROM 
(
select INVOICENO,ITEMID, CASES,CUSTNAME, CUSTADDR, REDISTID, CUSTOMER, DATE,BUYGROUP, BROKER, 
CUSTCITYSTATE, CUSTZIPCODE, BILLTONAME, BILLTOADDR, BILLTOCITYSTATE, BILLTOZIPCODE, INSERT_DATETIME,FILENAME,
ROW_NUMBER() OVER (PARTITION BY INVOICENO,ITEMID, CASES,CUSTNAME, CUSTADDR, REDISTID, CUSTOMER, DATE,BUYGROUP, BROKER, 
CUSTCITYSTATE, CUSTZIPCODE, BILLTONAME, BILLTOADDR, BILLTOCITYSTATE, BILLTOZIPCODE, INSERT_DATETIME ORDER BY FILENAME DESC) AS RN
from STAGE.YED_SALES
)
WHERE RN = 1;

DELETE FROM STAGE.YED_SALES;

INSERT INTO STAGE.YED_SALES
SELECT * FROM STAGE.YED_SALES_TEMP;

DROP TABLE STAGE.YED_SALES_TEMP;

COMMIT;

END;
$$
;