--liquibase formatted sql
				
--changeset CHANDRAMANIMATERIAL_PROD_HIERARCHY_EV_1 runOnChange:true failOnError:true
--comment metadata type reference table
-----------------------------------------------------------------------
--RECEF ID: RA_R2144  
--DATE: 2023-10-10
--DESCRIPTION: Material Product Hierarchy details
--------------------Change History (Traceability) -------------------------------
-- Defect:
-- Date:
-- Description:
---------------------------------------------------------------------------------
CREATE OR REPLACE VIEW SUPPLY_CHAIN.MATERIAL_PROD_HIERARCHY_EV AS
WITH MATERIAL AS
(
SELECT M.MATNR, ZMM_PRODH1, ZMM_PRODH2, ZMM_PRODH3, ZMM_PRODH4, ZMM_PRODH5, ZMM_PRODH6
FROM STAGE."0MATERIAL_ATTR" AS M
),

PH1 AS
(
SELECT DISTINCT PRODUCTHIERARCHY_1, TEXT
FROM STAGE.ZVCMM_T179$E
WHERE LANGUAGE = 'E'
AND PRODUCTHIERARCHYLEVEL = 1
),

PH2 AS
(
SELECT DISTINCT PRODUCTHIERARCHY_2, TEXT
FROM STAGE.ZVCMM_T179$E
WHERE LANGUAGE = 'E'
AND PRODUCTHIERARCHYLEVEL = 2
),

PH3 AS
(SELECT DISTINCT PRODUCTHIERARCHY_3, TEXT
FROM STAGE.ZVCMM_T179$E
WHERE LANGUAGE = 'E'
AND PRODUCTHIERARCHYLEVEL = 3
),

PH4 AS
(
SELECT DISTINCT PRODUCTHIERARCHY_4, TEXT
FROM STAGE.ZVCMM_T179$E
WHERE LANGUAGE = 'E'
AND PRODUCTHIERARCHYLEVEL = 4
),

PH5 AS
(
SELECT DISTINCT PRODUCTHIERARCHY_5, TEXT
FROM STAGE.ZVCMM_T179$E
WHERE LANGUAGE = 'E'
AND PRODUCTHIERARCHYLEVEL = 5
),

PH6 AS
(
SELECT DISTINCT PRODUCTHIERARCHY_6, TEXT
FROM STAGE.ZVCMM_T179$E
WHERE LANGUAGE = 'E'
AND PRODUCTHIERARCHYLEVEL = 6
)

SELECT MATERIAL.MATNR, 
MATERIAL.ZMM_PRODH1,
PH1.TEXT AS PRODUCT_LINE,
MATERIAL.ZMM_PRODH2,
PH2.TEXT AS PRODUCT_TYPE,
MATERIAL.ZMM_PRODH3,
PH3.TEXT AS BRAND_NAME,
MATERIAL.ZMM_PRODH4,
PH4.TEXT AS CATEGORY,
MATERIAL.ZMM_PRODH5,
PH5.TEXT AS SUB_CATEGORY,
MATERIAL.ZMM_PRODH6,
PH6.TEXT AS PACK_QUANTITY
FROM MATERIAL
 JOIN PH1 ON (MATERIAL.ZMM_PRODH1 = PH1.PRODUCTHIERARCHY_1)
 JOIN PH2 ON (MATERIAL.ZMM_PRODH2 = PH2.PRODUCTHIERARCHY_2)
 JOIN PH3 ON (MATERIAL.ZMM_PRODH3 = PH3.PRODUCTHIERARCHY_3)
 JOIN PH4 ON (MATERIAL.ZMM_PRODH4 = PH4.PRODUCTHIERARCHY_4)
 JOIN PH5 ON (MATERIAL.ZMM_PRODH5 = PH5.PRODUCTHIERARCHY_5)
 JOIN PH6 ON (MATERIAL.ZMM_PRODH6 = PH6.PRODUCTHIERARCHY_6);