--liquibase formatted sql
				
--changeset CHANDRAMANI:PBI_COND_CONTRACT_DTL_EV_7 runOnChange:true failOnError:true
--comment metadata type reference table
-----------------------------------------------------------------
--RECEF ID: RA_R2144  
--DATE: 2023-09-06
--DESCRIPTION:Condition Contract Detail for Redistributed sales report 
--------------------Change History (Traceability) -------------------------------
-- Defect:
-- Date:
-- Description:
---------------------------------------------------------------------------------

-- 531 Header. Grabbing condition contracts for type 531. 
-- Type 531 indicates condition contracts for broker and material.
CREATE OR REPLACE VIEW SUPPLY_CHAIN.PBI_COND_CONTRACT_DTL_EV AS 
WITH TABLE_531_CONTR AS
(
SELECT
CONDITIONCONTRACT,
SUPPLIER,
EXTERNALDOCUMENTREFERENCEID,
TABLENAME,
CNDNCONTRACT,
SALESAREA,
DISTCHANNEL,
DIVISION,
CUSTOMER,
MATERIAL,
DATEFROM,
DATETO,
AMOUNT,
AMOUNTTYPE,
UOM,
KSCHL
FROM
(SELECT 
DISTINCT
CONDITIONCONTRACT,
SUPPLIER,
--To extract Broker Number from EXTERNALDOCUMENTREFERENCEID -
--consider the First 3 characters of EXTERNALDOCUMENTREFERENCEID

-- The column is changing to X For deleted records - No action for active records i.e for active records we have spaces 
-- while filtering out Inactive records by <> condition we need to inlude NULL explicitly to inlude NULL Values  
CASE 
WHEN EXTERNALDOCUMENTREFERENCEID LIKE 'MORGAN MARKETING%' THEN '655' 
ELSE LEFT(EXTERNALDOCUMENTREFERENCEID, 3) END AS EXTERNALDOCUMENTREFERENCEID,
CNDNCONTRVALIDFROM AS DATEFROM,
CNDNCONTRVALIDTO AS DATETO
FROM STAGE.ZVCTPMCONDCONTRT$F
WHERE CNDNCONTRTYPE IN ('ZBC1','ZBG1') AND (CNDNCONTRISINACTIVE <> 'X' OR CNDNCONTRISINACTIVE IS NULL)
) AS CONDITION_HEADER
JOIN 
(
SELECT DISTINCT
KOTABNR AS TABLENAME,
COCO_NUM AS CNDNCONTRACT,
VKORG AS SALESAREA,
VTWEG AS DISTCHANNEL,
SPART AS DIVISION,
KUNNR AS CUSTOMER,
MATNR AS MATERIAL,
KBETR AS AMOUNT,
KONWA AS AMOUNTTYPE,
KSCHL,
KMEIN AS UOM
FROM 
(
SELECT DISTINCT
COCO_NUM,
KUNNR,
KOTABNR,
VKORG,
VTWEG,
SPART,
KNUMH,
MATNR,
KBETR,
KONWA,
KPEIN,
KMEIN,
KSCHL
FROM STAGE.ZDS_COND_CONT_PRICING WHERE LOEVM_KO <> 'X'
) d 
INNER JOIN (SELECT DISTINCT CONDITIONCONTRACT,PRODUCT,BROKER,CNDNCONTRTYPE from STAGE.ZVCTPM_CONBUSVOL$F) a
ON CONCAT(a.CONDITIONCONTRACT,a.PRODUCT) = CONCAT(d.COCO_NUM,d.MATNR)

) AS CONDITION_PRICING
ON CONDITION_HEADER.CONDITIONCONTRACT = CONDITION_PRICING.CNDNCONTRACT
WHERE  KSCHL IN ('ZBCC','ZAMW','ZBPR','ZOSC')  AND 
((TABLENAME = '531') OR (TABLENAME = '529'  AND LEFT(EXTERNALDOCUMENTREFERENCEID, 3) = '655') )
)
,


-- Joining the 531 header to redistibutor sales on broker and material. 
-- Invoice date must fall between the condtion contract from and to date.
PBI_YEDSALES_531 AS 
(
SELECT  
        TABLE_531_CONTR.CONDITIONCONTRACT, 
        TABLE_531_CONTR.SUPPLIER,
        TABLE_531_CONTR.EXTERNALDOCUMENTREFERENCEID,
        TABLE_531_CONTR.TABLENAME, 
        TABLE_531_CONTR.SALESAREA,
        TABLE_531_CONTR.DISTCHANNEL, 
        TABLE_531_CONTR.DIVISION,
        TABLE_531_CONTR.CUSTOMER,
        TABLE_531_CONTR.MATERIAL, 
        TABLE_531_CONTR.DATEFROM, 
        TABLE_531_CONTR.DATETO,
        TABLE_531_CONTR.AMOUNT,
        TABLE_531_CONTR.AMOUNTTYPE,
        TABLE_531_CONTR.UOM, 
        YS_531.BROKER, 
        YS_531.ITEMID, 
        YS_531.INVOICE_DATE,
		YS_531.FB_FLAG,
        CONCAT(TABLENAME, '-' , YS_531.BROKER , '-', YS_531.ITEMID ,'-', YS_531.INVOICE_DATE) AS SKEY
FROM SUPPLY_CHAIN.YED_SALES_WITH_PRICING AS YS_531 
LEFT JOIN
TABLE_531_CONTR 
ON YS_531.BROKER = TABLE_531_CONTR.EXTERNALDOCUMENTREFERENCEID 
AND YS_531.ITEMID = TABLE_531_CONTR.MATERIAL
AND YS_531.INVOICE_DATE BETWEEN TABLE_531_CONTR.DATEFROM and TABLE_531_CONTR.DATETO
WHERE TABLE_531_CONTR.EXTERNALDOCUMENTREFERENCEID IS NOT NULL),

-- 530 and 528 Header. Grabbing condition contracts for type 530 and 528. 
-- Type 530 and 528 indicates condition contracts for broker only.
TABLE_530528_CONTR AS (
SELECT
CONDITIONCONTRACT,
SUPPLIER,
EXTERNALDOCUMENTREFERENCEID,
TABLENAME,
CNDNCONTRACT,
SALESAREA,
DISTCHANNEL,
DIVISION,
CUSTOMER,
MATERIAL,
DATEFROM,
DATETO,
AMOUNT,
AMOUNTTYPE,
UOM,
KSCHL
FROM
(SELECT DISTINCT
CONDITIONCONTRACT,
SUPPLIER,
CASE 
WHEN EXTERNALDOCUMENTREFERENCEID LIKE 'MORGAN MARKETING%' THEN '655' 
ELSE LEFT(EXTERNALDOCUMENTREFERENCEID, 3) END AS EXTERNALDOCUMENTREFERENCEID,
CNDNCONTRVALIDFROM AS DATEFROM,
CNDNCONTRVALIDTO AS DATETO
FROM STAGE.ZVCTPMCONDCONTRT$F 
WHERE CNDNCONTRTYPE IN ('ZBC1','ZBG1') AND (CNDNCONTRISINACTIVE <> 'X' OR CNDNCONTRISINACTIVE IS NULL)
) AS CONDITION_HEADER
JOIN 
(
SELECT DISTINCT
KOTABNR AS TABLENAME,
COCO_NUM AS CNDNCONTRACT,
VKORG AS SALESAREA,
VTWEG AS DISTCHANNEL,
SPART AS DIVISION,
KUNNR AS CUSTOMER,
MATNR AS MATERIAL,
KBETR AS AMOUNT,
KONWA AS AMOUNTTYPE,
KMEIN AS UOM,
KSCHL
FROM 
(
SELECT DISTINCT 
COCO_NUM,
KUNNR,
KOTABNR,
VKORG,
VTWEG,
SPART,
KNUMH,
MATNR,
KBETR,
KONWA,
KPEIN,
KMEIN,
KSCHL
FROM STAGE.ZDS_COND_CONT_PRICING WHERE LOEVM_KO <> 'X'
) d
INNER JOIN (SELECT DISTINCT CONDITIONCONTRACT,PRODUCT,BROKER,CNDNCONTRTYPE from STAGE.ZVCTPM_CONBUSVOL$F) a
ON a.CONDITIONCONTRACT = d.COCO_NUM  
WHERE KSCHL IN ('ZBCC','ZAMW','ZBPR','ZOSC')  AND KOTABNR IN ('530','528')) AS CONDITION_PRICING
ON CONDITION_HEADER.CONDITIONCONTRACT = CONDITION_PRICING.CNDNCONTRACT

),

-- Joining the 531 header to redistibutor sales on broker and material. 
-- Invoice date must fall between the condtion contract from and to date.

PBI_YEDSALES_530528 AS (
SELECT 
    TABLE_530528_CONTR.CONDITIONCONTRACT, 
    TABLE_530528_CONTR.SUPPLIER,
    TABLE_530528_CONTR.EXTERNALDOCUMENTREFERENCEID,
    TABLE_530528_CONTR.TABLENAME, 
    TABLE_530528_CONTR.SALESAREA,
    TABLE_530528_CONTR.DISTCHANNEL, 
    TABLE_530528_CONTR.DIVISION,
    TABLE_530528_CONTR.CUSTOMER,
    TABLE_530528_CONTR.MATERIAL, 
    TABLE_530528_CONTR.DATEFROM, 
    TABLE_530528_CONTR.DATETO,
    TABLE_530528_CONTR.AMOUNT,
    TABLE_530528_CONTR.AMOUNTTYPE,
    TABLE_530528_CONTR.UOM,
    YED_530528.BROKER, 
    YED_530528.ITEMID, 
    YED_530528.INVOICE_DATE,
	YED_530528.FB_FLAG,
    CONCAT(TABLENAME, '-' , YED_530528.BROKER , '-', YED_530528.ITEMID ,'-', YED_530528.INVOICE_DATE) AS SKEY
FROM
(SELECT 
    YS_531.BROKER, 
    YS_531.ITEMID, 
    YS_531.INVOICE_DATE,
    YS_531.FB_FLAG
FROM SUPPLY_CHAIN.YED_SALES_WITH_PRICING AS YS_531 
LEFT JOIN
TABLE_531_CONTR 
ON YS_531.BROKER = TABLE_531_CONTR.EXTERNALDOCUMENTREFERENCEID 
AND YS_531.ITEMID = TABLE_531_CONTR.MATERIAL
AND YS_531.INVOICE_DATE BETWEEN TABLE_531_CONTR.DATEFROM and TABLE_531_CONTR.DATETO
WHERE TABLE_531_CONTR.EXTERNALDOCUMENTREFERENCEID IS NULL) AS YED_530528
JOIN 
TABLE_530528_CONTR
ON YED_530528.BROKER = TABLE_530528_CONTR.EXTERNALDOCUMENTREFERENCEID 
AND YED_530528.INVOICE_DATE BETWEEN TABLE_530528_CONTR.DATEFROM and TABLE_530528_CONTR.DATETO
WHERE EXTERNALDOCUMENTREFERENCEID IS NOT NULL)

SELECT 
    CONDITIONCONTRACT, 
    SUPPLIER,
    EXTERNALDOCUMENTREFERENCEID,
    TABLENAME, 
    SALESAREA,
    DISTCHANNEL, 
    DIVISION,
    CUSTOMER,
    MATERIAL, 
    DATEFROM, 
    DATETO,
    CASE WHEN AMOUNTTYPE <> '%' THEN (AMOUNT * -1)/100 
         WHEN AMOUNTTYPE = '%' THEN (AMOUNT * -1)/10
         ELSE NULL END AS AMOUNT,
    AMOUNTTYPE,
    UOM,
    BROKER, 
    ITEMID, 
    INVOICE_DATE,
	FB_FLAG,
    SKEY
FROM PBI_YEDSALES_530528

UNION

SELECT 
CONDITIONCONTRACT, 
    SUPPLIER,
    EXTERNALDOCUMENTREFERENCEID,
    TABLENAME, 
    SALESAREA,
    DISTCHANNEL, 
    DIVISION,
    CUSTOMER,
    MATERIAL, 
    DATEFROM, 
    DATETO,
    CASE WHEN AMOUNTTYPE <> '%' THEN (AMOUNT * -1)/100 
         WHEN AMOUNTTYPE = '%' THEN (AMOUNT * -1)/10
         ELSE NULL END AS AMOUNT,
    AMOUNTTYPE,
    UOM,
    BROKER, 
    ITEMID, 
    INVOICE_DATE,
	FB_FLAG,
    SKEY
FROM
PBI_YEDSALES_531