--liquibase formatted sql
				
--changeset CHANDRAMANI:PRICING_WITH_HISTORY_EV_9 runOnChange:true failOnError:true
--comment metadata type reference table
----------------------------------------------------------------
--RECEF ID: RA_R2144  
--DATE: 2023-09-01
--DESCRIPTION: This view is used to combine pricing details (billing condition and Pricing elements)
-- and Pricing history from the Fall back table 
-- Pricing date and Invoice Price for Sold to party, Material Granularity, 
-- Flag will show from where we are brining pricing details 
--------------------Change History (Traceability) -------------------------------
-- Defect:# 5236
-- Date: 2023-10-19
-- Description: Change selling price calculation to SellingPricing - Rebates - Freight - Cash Discount 
---------------------------------------------------------------------------------
CREATE OR REPLACE view SUPPLY_CHAIN.PRICING_WITH_HISTORY_EV AS
WITH REDIS AS
(
SELECT DISTINCT a.IDNUMBER,a.PARTNER PARTNER,b.PARTNER PARTNER_S
FROM 
(
SELECT DISTINCT IDNUMBER, PARTNER FROM STAGE."0BP_ID_ATTR" 
WHERE TYPE = 'ZBUP10'  AND IDNUMBER NOT LIKE '%1'
)  a
LEFT JOIN 
(
SELECT DISTINCT IDNUMBER, PARTNER FROM STAGE."0BP_ID_ATTR" 
WHERE TYPE = 'ZBUP10'  AND IDNUMBER NOT LIKE '%1'
UNION 
SELECT DISTINCT LEFT(IDNUMBER,LENGTH(IDNUMBER)-1) IDNUMBER,PARTNER FROM STAGE."0BP_ID_ATTR"
WHERE TYPE = 'ZBUP10' AND IDNUMBER LIKE '%1'
) b
on a.IDNUMBER = b.IDNUMBER
),

COND_PRICING  AS
(
------Pricing date and Invoice price for Present day for SOLD TO PARTY and MATERIAL
--SELECT SOLDTOPARTY,MATERIAL,PRICINGDATE,AMOUNT/QUANTITY_IN_LB AS INVOICE_PRICE, 'CP' AS FLAG FROM 
--(
SELECT  DISTINCT 
a.PRICINGDOCUMENT,
a.MATERIAL,
a.SOLDTOPARTY,--PRIMARY PARTNER 
a.PRICINGDATE,
IFNULL(a.SUBTOTAL5AMOUNT,0) AS SUBTOTAL5AMOUNT,
IFNULL(f.FREIGHT,0) FREIGHT,
IFNULL(r.REBATE,0) REBATE,
IFNULL(c.CASH_DISCOUNT,0) CASH_DISCOUNT,
IFNULL(f.KPEIN,0) AS KPEIN,
m.UMREZ,
m.UMREN
from 
(
SELECT DISTINCT a.BILLINGDOCUMENT,a.BILLINGDOCUMENTITEM,--b.BILLINGDOCUMENT,b.BILLINGDOCUMENTITEM, Keeping for validation purpose 
a.PRICINGDOCUMENT,a.PRICINGDOCUMENTITEM,
a.PRICINGPROCEDURESTEP,
a.PRICINGPROCEDURECOUNTER,
LTRIM(a.MATERIAL, '0') as MATERIAL,
a.SOLDTOPARTY,
a.CONDITIONTYPE, 
a.PRICINGDATE,
b.SUBTOTAL5AMOUNT
FROM STAGE.ZVCSD_BILLCOND$F a
LEFT JOIN STAGE.ZVCSD_BILLITEM$F b
on a.BILLINGDOCUMENT = b.BILLINGDOCUMENT and a.BILLINGDOCUMENTITEM = b.BILLINGDOCUMENTITEM
WHERE a.CONDITIONINACTIVEREASON = ' ' AND a.CONDITIONTYPE IN ('ZPR0','ZPR1') 
) a
LEFT JOIN 
(
SELECT DISTINCT 
KNUMV,
KPOSN,
KMEIN,
WAERS,
KPEIN,
KWERT AS FREIGHT,
KSCHL 
FROM STAGE.ZVCSD_PRCD_ELEM$F
WHERE KSCHL IN ('ZF00','ZFBG','ZFSC','ZFRA','ZFRF','ZFVS','ZF01', 'ZFFR')
) f 
ON a.PRICINGDOCUMENT = f.KNUMV AND a.PRICINGDOCUMENTITEM = f.KPOSN
LEFT JOIN 
(
SELECT DISTINCT 
KNUMV,
KPOSN,
KMEIN,
WAERS,
KPEIN,
KWERT AS REBATE,
KSCHL 
FROM STAGE.ZVCSD_PRCD_ELEM$F
WHERE KSCHL IN 
('ZAAT','ZABG','ZAER','ZAEW','ZAGR','ZAGW','ZAMR','ZAMW','ZAPP','ZAPR','ZAPU','ZAPW','ZASR','ZASW','ZFAO',
'ZFCR','ZFCW','ZGGR','ZGGW','ZGIP','ZGIR','ZMDV','ZMFP','ZMFV','ZMMF','ZMML','ZMMP','ZMMR','ZMSR','ZORI', 
'ZRIP','ZRIR','ZSLA')
) r 
ON a.PRICINGDOCUMENT = r.KNUMV AND a.PRICINGDOCUMENTITEM = r.KPOSN
LEFT JOIN 
(
SELECT DISTINCT 
KNUMV,
KPOSN,
KMEIN,
WAERS,
KPEIN,
KWERT AS CASH_DISCOUNT,
KSCHL
FROM STAGE.ZVCSD_PRCD_ELEM$F
WHERE KSCHL = 'SKTO'
) c 
ON a.PRICINGDOCUMENT = c.KNUMV AND a.PRICINGDOCUMENTITEM = c.KPOSN
LEFT JOIN (SELECT DISTINCT LTRIM(MATNR, '0') AS MATNR,MEINH, EAN11,UMREZ,UMREN FROM STAGE."0MAT_UNIT_ATTR" WHERE MEINH = 'LB') m
ON a.MATERIAL = m.MATNR 
INNER JOIN REDIS p
ON (a.SOLDTOPARTY = p.PARTNER OR a.SOLDTOPARTY = p.PARTNER_S) -- to consider secondary partner for each IDNUMBER
),

COND_PRICING_ELEMENT  AS
(
SELECT 
MATERIAL,
SOLDTOPARTY,--PRIMARY PARTNER 
PRICINGDATE,
(SUM(SUBTOTAL5AMOUNT) - SUM(FREIGHT) + SUM(REBATE) + SUM(CASH_DISCOUNT)) / 
(SUM(KPEIN)/(SUM(UMREZ)/SUM(UMREN)))/COUNT(DISTINCT PRICINGDOCUMENT) AS INVOICE_PRICE, 
'CP' AS FLAG
FROM COND_PRICING
WHERE KPEIN > 0 
GROUP BY 
MATERIAL,
SOLDTOPARTY,--PRIMARY PARTNER 
PRICINGDATE
),

FALL_BACK AS
(
------Pricing date and Invoice price for History from Fall back Table for SOLD TO PARTY and MATERIAL
SELECT p.PARTNER AS SOLDTOPARTY, --PRIMARY PARTNER 
LTRIM(ITEM, '0') AS MATERIAL,INVDATE AS PRICINGDATE,
(sum(NVL(DOLLARS,0)) - sum(NVL(FREIGHT,0)) - sum(NVL(REBATES,0)) - sum(NVL(CASHDISC,0)) ) / sum(NVL(LBS,0)) as INVOICE_PRICE,
'FB' AS FLAG
FROM SUPPLY_CHAIN.SALEDAY_TBL_MV  SD
INNER JOIN 
(SELECT DISTINCT PARTNER, BPEXT, BU_SORT1 FROM STAGE."0BPARTNER_ATTR") AS BP
ON TO_VARCHAR(SD.SHIPTTO) = BP.BPEXT   --- SHIPTTO Is Numeric Data type from source we converting this to varchar  
INNER JOIN REDIS p
ON (BP.PARTNER = p.PARTNER OR BP.PARTNER = p.PARTNER_S) 
WHERE DOLLARS > 0 and LBS > 0 
group by 
LTRIM(ITEM, '0'),
INVDATE,
p.PARTNER
-------------------
)

SELECT SOLDTOPARTY,MATERIAL,PRICINGDATE,INVOICE_PRICE,FLAG FROM COND_PRICING_ELEMENT
UNION 
SELECT SOLDTOPARTY,MATERIAL,PRICINGDATE,INVOICE_PRICE,FLAG FROM FALL_BACK
;