--liquibase formatted sql
				
--changeset CHANDRAMANI:YED_SALES_WITH_COND_CONTRACT_EV_7 runOnChange:true failOnError:true
--comment metadata type reference table

------------------------------------------------------------------------
--RECEF ID: RA_R2144  
--DATE: 2023-09-01
--DESCRIPTION: Joiining Yed sales with pricing dates with condition contract dat set 
--------------------Change History (Traceability) -------------------------------
-- Defect:
-- Date:
-- Description:
---------------------------------------------------------------------------------

CREATE OR REPLACE view SUPPLY_CHAIN.YED_SALES_WITH_COND_CONTRACT_EV AS
WITH CC_HDR_531 AS 
(
select DISTINCT
a.SUPPLIER,
LEFT(a.EXTERNALDOCUMENTREFERENCEID,3) EXTERNALDOCUMENTREFERENCEID,
d.COCO_NUM,
d.KOTABNR,
d.MATERIAL,
a.DateFrom,
a.DateTo,
d.AMOUNT,
d.AMT_TYPE,
d.UnitofMeasure,
CASE WHEN d.KOTABNR = '531' THEN 1 
     WHEN ( d.KOTABNR = '529' AND LEFT(a.EXTERNALDOCUMENTREFERENCEID,3) = '655') THEN 1 ELSE 0 END AS FLAG
FROM
(
SELECT DISTINCT 
CONDITIONCONTRACT, 
CNDNCONTRTYPE,
SUPPLIER,
CASE WHEN EXTERNALDOCUMENTREFERENCEID LIKE 'MORGAN MARKETING%' THEN '655' ELSE EXTERNALDOCUMENTREFERENCEID END AS EXTERNALDOCUMENTREFERENCEID,
CNDNCONTRVALIDFROM DateFrom,
CNDNCONTRVALIDTO DateTo
FROM STAGE.ZVCTPMCONDCONTRT$F 
WHERE CNDNCONTRTYPE IN ('ZBC1','ZBG1') AND (CNDNCONTRISINACTIVE <> 'X' OR CNDNCONTRISINACTIVE IS NULL)
) a
-- The column is changing to X For deleted records - No action for active records i.e for active records we have spaces 
-- while filtering out Inactive records by <> condition we need to inlude NULL explicitly to inlude NULL Values  
INNER JOIN 
(
SELECT DISTINCT 
d.COCO_NUM,
d.KUNNR,
d.KOTABNR,
d.VKORG SALES_AREA,
d.VTWEG DIST_CHANNEL,
d.SPART DIVISION,
d.KNUMH ConditionRecordNo,
d.MATNR AS MATERIAL,
--DATAB DateFrom,
--DATBI DateTo,
d.KBETR AMOUNT,
d.KONWA AMT_TYPE,
d.KPEIN as PricingUnit,
d.KMEIN as UnitofMeasure
FROM 
(
SELECT DISTINCT 
COCO_NUM,
KUNNR,
KOTABNR,
VKORG,
VTWEG,
SPART,
KNUMH,
MATNR,
KBETR,
KONWA,
KPEIN,
KMEIN,
KSCHL
FROM STAGE.ZDS_COND_CONT_PRICING WHERE LOEVM_KO <> 'X'
) d
INNER JOIN (SELECT DISTINCT CONDITIONCONTRACT,PRODUCT,BROKER,CNDNCONTRTYPE from STAGE."ZVCTPM_CONBUSVOL$F") a
ON CONCAT(a.CONDITIONCONTRACT,a.PRODUCT) = CONCAT(d.COCO_NUM,d.MATNR)
WHERE d.KSCHL IN ('ZBCC','ZAMW','ZBPR','ZOSC') AND d.KOTABNR IN ('531','529')  
) d
ON a.CONDITIONCONTRACT = d.COCO_NUM
WHERE FLAG = 1
),

-- Joining the 531 header to redistibutor sales on broker and material. 
-- Invoice date must fall between the condtion contract from and to date.

YS_531 AS
(
SELECT 
b.SUPPLIER,
b.EXTERNALDOCUMENTREFERENCEID,
b.COCO_NUM,
b.KOTABNR,
b.DateFrom,
b.DateTo,
b.AMOUNT,
b.AMT_TYPE, 
a.FILENAME,
a.REDISTID,
a.BUYGROUP,
a.BROKER,
a.CUSTNAME,
a.CUSTOMER,
a.CUSTADDR,
a.CUSTCITYSTATE,
a.ITEMID,
a.INVOICENO,
a.CASE_QTY,
a.MATNR,
a.Weight,
a.Unit,
a.Brand,
a.ProductStyle,
a.UPC, 
a.TXTMD,
a.REDIS_NUMBER,
a.SOLDTOPARTY,
a.INVOICE_PRICE,
a.INVOICE_DATE,
a.PRICINGDATE,
CONCAT(b.KOTABNR, '-' , a.BROKER , '-', a.ITEMID ,'-', a.INVOICE_DATE) AS SKEY,
'Y' AS COND_CONTRACT_FLAG,
a.FB_FLAG
FROM SUPPLY_CHAIN.YED_SALES_WITH_PRICING AS a 
LEFT JOIN CC_HDR_531 b 
ON a.BROKER = b.EXTERNALDOCUMENTREFERENCEID 
AND a.ITEMID = b.MATERIAL
AND a.INVOICE_DATE BETWEEN b.DateFrom and b.DateTo
WHERE b.EXTERNALDOCUMENTREFERENCEID IS NOT NULL
),

--SELECT * FROM YS_531;

CC_HDR_530 AS 
(
select 
a.SUPPLIER,
LEFT(a.EXTERNALDOCUMENTREFERENCEID,3) EXTERNALDOCUMENTREFERENCEID,
d.COCO_NUM,
d.KOTABNR,
d.MATERIAL,
a.DateFrom,
a.DateTo,
d.AMOUNT,
d.AMT_TYPE,
d.UnitofMeasure
FROM
(
SELECT DISTINCT 
CONDITIONCONTRACT, 
CNDNCONTRTYPE,
SUPPLIER,
CASE WHEN EXTERNALDOCUMENTREFERENCEID LIKE 'MORGAN MARKETING%' THEN '655' ELSE EXTERNALDOCUMENTREFERENCEID END AS EXTERNALDOCUMENTREFERENCEID,
CNDNCONTRVALIDFROM DateFrom,
CNDNCONTRVALIDTO DateTo
FROM STAGE.ZVCTPMCONDCONTRT$F WHERE CNDNCONTRTYPE IN ('ZBC1','ZBG1') AND (CNDNCONTRISINACTIVE <> 'X' OR CNDNCONTRISINACTIVE IS NULL)
) a
INNER JOIN 
(
SELECT DISTINCT 
d.COCO_NUM,
d.KUNNR,
d.KOTABNR,
d.VKORG SALES_AREA,
d.VTWEG DIST_CHANNEL,
d.SPART DIVISION,
d.KNUMH ConditionRecordNo,
d.MATNR AS MATERIAL,
--DATAB DateFrom,
--DATBI DateTo,
d.KBETR AMOUNT,
d.KONWA AMT_TYPE,
d.KPEIN as PricingUnit,
d.KMEIN as UnitofMeasure
FROM 
(
SELECT DISTINCT 
COCO_NUM,
KUNNR,
KOTABNR,
VKORG,
VTWEG,
SPART,
KNUMH,
MATNR,
KBETR,
KONWA,
KPEIN,
KMEIN,
KSCHL
FROM STAGE.ZDS_COND_CONT_PRICING WHERE LOEVM_KO <> 'X'
)  d
INNER JOIN (SELECT DISTINCT CONDITIONCONTRACT,PRODUCT,BROKER,CNDNCONTRTYPE from STAGE."ZVCTPM_CONBUSVOL$F") a
ON a.CONDITIONCONTRACT = d.COCO_NUM 
WHERE KSCHL IN ('ZBCC','ZAMW','ZBPR','ZOSC') AND KOTABNR IN ('528','530')
) d
ON a.CONDITIONCONTRACT = d.COCO_NUM
),

--SELECT * FROM CC_HDR_530;
-- 530 and 528 Header. Grabbing condition contracts for type 530 and 528. 
-- Type 530 and 528 indicates condition contracts for broker only.

YS_530_NULL AS
(
SELECT 
b.SUPPLIER,
b.EXTERNALDOCUMENTREFERENCEID,
b.COCO_NUM,
b.KOTABNR,
b.DateFrom,
b.DateTo,
b.AMOUNT,
b.AMT_TYPE, 
a.FILENAME,
a.REDISTID,
a.BUYGROUP,
a.BROKER,
a.CUSTNAME,
a.CUSTOMER,
a.CUSTADDR,
a.CUSTCITYSTATE,
a.ITEMID,
a.INVOICENO,
a.CASE_QTY,
a.MATNR,
a.Weight,
a.Unit,
a.Brand,
a.ProductStyle,
a.UPC, 
a.TXTMD,
a.REDIS_NUMBER,
a.SOLDTOPARTY,
a.INVOICE_PRICE,
a.INVOICE_DATE,
a.PRICINGDATE,
a.FB_FLAG
FROM SUPPLY_CHAIN.YED_SALES_WITH_PRICING a
LEFT JOIN CC_HDR_531 b
ON a.BROKER = b.EXTERNALDOCUMENTREFERENCEID 
AND a.ITEMID = b.MATERIAL
AND a.INVOICE_DATE BETWEEN b.DateFrom and b.DateTo
WHERE b.EXTERNALDOCUMENTREFERENCEID IS NULL
),

--select * from YS_530_NULL;

YS_530 AS
(
SELECT 
b.SUPPLIER,
b.EXTERNALDOCUMENTREFERENCEID,
b.COCO_NUM,
b.KOTABNR,
b.DateFrom,
b.DateTo,
b.AMOUNT,
b.AMT_TYPE, 
a.FILENAME,
a.REDISTID,
a.BUYGROUP,
a.BROKER,
a.CUSTNAME,
a.CUSTOMER,
a.CUSTADDR,
a.CUSTCITYSTATE,
a.ITEMID,
a.INVOICENO,
a.CASE_QTY,
a.MATNR,
a.Weight,
a.Unit,
a.Brand,
a.ProductStyle,
a.UPC, 
a.TXTMD,
a.REDIS_NUMBER,
a.SOLDTOPARTY,
a.INVOICE_PRICE,
a.INVOICE_DATE,
a.PRICINGDATE,
CONCAT(b.KOTABNR, '-' , a.BROKER , '-', a.ITEMID ,'-', a.INVOICE_DATE) AS SKEY,
'Y' AS COND_CONTRACT_FLAG,
a.FB_FLAG
FROM YS_530_NULL a
INNER JOIN CC_HDR_530 b
ON a.BROKER = b.EXTERNALDOCUMENTREFERENCEID 
AND a.INVOICE_DATE BETWEEN b.DateFrom and b.DateTo
WHERE b.EXTERNALDOCUMENTREFERENCEID IS NOT NULL
),

--select * from YS_530;

YS_NO_COND_CONTRACT AS
(
SELECT 
b.SUPPLIER,
b.EXTERNALDOCUMENTREFERENCEID,
b.COCO_NUM,
b.KOTABNR,
b.DateFrom,
b.DateTo,
b.AMOUNT,
b.AMT_TYPE, 
a.FILENAME,
a.REDISTID,
a.BUYGROUP,
a.BROKER,
a.CUSTNAME,
a.CUSTOMER,
a.CUSTADDR,
a.CUSTCITYSTATE,
a.ITEMID,
a.INVOICENO,
a.CASE_QTY,
a.MATNR,
a.Weight,
a.Unit,
a.Brand,
a.ProductStyle,
a.UPC, 
a.TXTMD,
a.REDIS_NUMBER,
a.SOLDTOPARTY,
a.INVOICE_PRICE,
a.INVOICE_DATE,
a.PRICINGDATE,
CONCAT(b.KOTABNR, '-' , a.BROKER , '-', a.ITEMID ,'-', a.INVOICE_DATE) AS SKEY,
'N' AS COND_CONTRACT_FLAG,
a.FB_FLAG
FROM YS_530_NULL a
LEFT JOIN CC_HDR_530 b
ON a.BROKER = b.EXTERNALDOCUMENTREFERENCEID 
AND a.INVOICE_DATE BETWEEN b.DateFrom and b.DateTo
WHERE b.EXTERNALDOCUMENTREFERENCEID IS NULL
)

SELECT 
SUPPLIER,
EXTERNALDOCUMENTREFERENCEID,
COCO_NUM,
KOTABNR,
DateFrom,
DateTo,
(AMOUNT * -1) AS AMOUNT,
AMT_TYPE, 
FILENAME,
REDISTID,
BUYGROUP,
BROKER,
CUSTNAME,
CUSTOMER,
CUSTADDR,
CUSTCITYSTATE,
ITEMID,
INVOICENO,
CASE_QTY,
MATNR,
Weight,
Unit,
Brand,
ProductStyle,
UPC, 
TXTMD,
REDIS_NUMBER,
SOLDTOPARTY,
INVOICE_PRICE,
INVOICE_DATE,
PRICINGDATE,
SKEY,
COND_CONTRACT_FLAG,
FB_FLAG
FROM YS_531

UNION

SELECT 
SUPPLIER,
EXTERNALDOCUMENTREFERENCEID,
COCO_NUM,
KOTABNR,
DateFrom,
DateTo,
(AMOUNT * -1) AS AMOUNT,
AMT_TYPE, 
FILENAME,
REDISTID,
BUYGROUP,
BROKER,
CUSTNAME,
CUSTOMER,
CUSTADDR,
CUSTCITYSTATE,
ITEMID,
INVOICENO,
CASE_QTY,
MATNR,
Weight,
Unit,
Brand,
ProductStyle,
UPC, 
TXTMD,
REDIS_NUMBER,
SOLDTOPARTY,
INVOICE_PRICE,
INVOICE_DATE,
PRICINGDATE,
SKEY,
COND_CONTRACT_FLAG,
FB_FLAG 
FROM YS_530

UNION 

SELECT 
SUPPLIER,
EXTERNALDOCUMENTREFERENCEID,
COCO_NUM,
KOTABNR,
DateFrom,
DateTo,
(AMOUNT * -1) AS AMOUNT,
AMT_TYPE, 
FILENAME,
REDISTID,
BUYGROUP,
BROKER,
CUSTNAME,
CUSTOMER,
CUSTADDR,
CUSTCITYSTATE,
ITEMID,
INVOICENO,
CASE_QTY,
MATNR,
Weight,
Unit,
Brand,
ProductStyle,
UPC, 
TXTMD,
REDIS_NUMBER,
SOLDTOPARTY,
INVOICE_PRICE,
INVOICE_DATE,
PRICINGDATE,
SKEY,
COND_CONTRACT_FLAG,
FB_FLAG
FROM YS_NO_COND_CONTRACT;
