--liquibase formatted sql
				
--changeset CHANDRAMANI:METADATA_DATATYPE_REFERENCE_TBL_1 runOnChange:true failOnError:true
--comment metadata type reference table
create or replace view METADATA_SUMMARY_VW(
	TABLE_NAME COMMENT 'Table Name',
	DATASOURCE COMMENT 'BODS Extract Structure',
	SEGMENT COMMENT 'For Hierarchy Datasets Sets Table Granularity',
	FIELDNAME COMMENT 'Name Of Extract Column',
	ORDINAL_POSITION COMMENT 'Column Order Number',
	SNOWFLAKE_TYPE COMMENT 'Datatype In Snowflake',
	FIELD_LENGTH COMMENT 'Length Of The Column After Being Transformed By SAP Application Layer Logic',
	DECIMAL_PRECISION COMMENT 'Decimal Precision',
	FIELD_DESCRIPTION COMMENT 'Column Description',
	TABLE_DESCRIPTION COMMENT 'Table Description'
) COMMENT='Curated join of tables METADATA_STORE_TBL and METADATA_DATATYPE_REFERENCE_TBL to display metadata relevant to Snowflake'
 as
select 
    CASE WHEN A.SEGMENT IS NULL OR A.SEGMENT = ' ' THEN A.DATASOURCE ELSE CONCAT(A.DATASOURCE,'_',A.SEGMENT) END AS TABLE_NAME,
    A.DATASOURCE,A.SEGMENT,A.FIELDNAME,A.POSN AS ORDINAL_POSITION,
    CASE WHEN C.SNOWFLAKE_TYPE IS NOT NULL THEN C.SNOWFLAKE_TYPE WHEN B.SNOWFLAKE_TYPE IS NULL THEN '@' ELSE B.SNOWFLAKE_TYPE END AS SNOWFLAKE_TYPE,
    CASE WHEN B.SNOWFLAKE_TYPE = 'DATE' THEN 10 WHEN B.SNOWFLAKE_TYPE = 'TIME' THEN 8 ELSE A.OUTPUTLENG END AS FIELD_LENGTH,
    A.DECIMALS AS DECIMAL_PRECISION,A.DESCRIPTION AS FIELD_DESCRIPTION,A.DSRC_TXTLG AS TABLE_DESCRIPTION
from METADATA_STORE_TBL AS A 
LEFT OUTER JOIN METADATA_DATATYPE_REFERENCE_TBL AS B ON B.SAP_TYPE = A.TYPE  AND B.OVERRIDE_TABLE IS NULL  AND B.OVERRIDE_COLUMN IS NULL
LEFT OUTER JOIN METADATA_DATATYPE_REFERENCE_TBL AS C ON C.SAP_TYPE = A.TYPE  AND C.OVERRIDE_TABLE = CASE WHEN A.SEGMENT = ' ' THEN A.DATASOURCE ELSE CONCAT(A.DATASOURCE,'_',A.SEGMENT) END  AND C.OVERRIDE_COLUMN = A.FIELDNAME
ORDER BY TABLE_NAME, ORDINAL_POSITION;